baseURL = "https://cv.l3x.in"
languageCode = "en-us"
title = "Alexander Fortin's curriculum vitae"

[params]
  author = "Alexander Fortin"
  workTitle = "Full Stack Software Engineer"
  githubLink = "https://github.com/shaftoe/curriculum-vitae"
  photoLink = "https://ibin.co/59LCiiM0Y00G.jpg"
