baseURL = "https://cv.l3x.in"
languageCode = "en-us"
title = "Alexander Fortin's curriculum vitae"
googleAnalytics = "UA-157359136-1"
enableGitInfo = true
disableKinds = ["taxonomy", "taxonomyTerm"] # https://discourse.gohugo.io/t/found-no-layout-for-taxonomyterm-language-en-output-format-html/16376/2

[params]
  author = "Alexander Fortin"
  workTitle = "Full Stack Software Engineer"
  description = "Alexander Fortin's curriculum vitae, always up to date and available as an accessible responsive web site"
  githubLink = "https://github.com/shaftoe/curriculum-vitae"
  contactLink = "https://a.l3x.in/contact/"
